name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install NPM Dependencies
      run: npm install

    - name: Build NPM Assets
      run: npm run build

      - name: Deploy to Plesk
        env:
          PLESK_USERNAME: ${{ secrets.PLESK_USERNAME }}
          PLESK_PASSWORD: ${{ secrets.PLESK_PASSWORD }}
          PLESK_HOST: ${{ secrets.PLESK_HOST }}
        run: |
          sshpass -p $PLESK_PASSWORD ssh -o StrictHostKeyChecking=no $PLESK_USERNAME@$PLESK_HOST << 'EOF'
          cd /var/www/vhosts/yourdomain.com/httpdocs  # Adjust path as necessary
          git pull origin main  # Pull the latest code from the repository
          composer install --no-dev --optimize-autoloader  # Install PHP dependencies
          npm install  # Install JS dependencies if necessary
          npm run build  # Run the build process if applicable
          php artisan migrate --force  # Run migrations if necessary
          EOF
