name: Deploy to Plesk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Specify your PHP version

      - name: Install Dependencies
        run: |
          composer install
          npm install
          npm run build  # Build assets using npm if needed

      - name: Deploy to Plesk
        env:
          PLESK_USERNAME: ${{ secrets.PLESK_USERNAME }}
          PLESK_PASSWORD: ${{ secrets.PLESK_PASSWORD }}
          PLESK_HOST: ${{ secrets.PLESK_HOST }}
        run: |
          sshpass -p $PLESK_PASSWORD ssh -o StrictHostKeyChecking=no $PLESK_USERNAME@$PLESK_HOST << 'EOF'
          cd /var/www/vhosts/yourdomain.com/httpdocs  # Adjust path as necessary
          git pull origin main  # Pull the latest code from the repository
          composer install --no-dev --optimize-autoloader  # Install PHP dependencies
          npm install  # Install JS dependencies if necessary
          npm run build  # Run the build process if applicable
          php artisan migrate --force  # Run migrations if necessary
          EOF
